package configs

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool" // ✅ 1. เพิ่มแพ็กเกจ pgxpool
	"github.com/joho/godotenv"
)

// ✅ 2. เปลี่ยนชนิดตัวแปรเป็น *pgxpool.Pool
var DB *pgxpool.Pool
var SupabaseProjectRef string

func ConnectDB() {
	// 1. โหลด .env
	err := godotenv.Load()
	if err != nil {
		log.Println("Warning: No .env file found")
	}

	// 2. โหลด Database URL
	databaseURL := os.Getenv("DATABASE_URL")
	if databaseURL == "" {
		log.Fatal("DATABASE_URL is not set")
	}

	SupabaseProjectRef = os.Getenv("SUPABASE_PROJECT_REF")
	if SupabaseProjectRef == "" {
		log.Fatal("SUPABASE_PROJECT_REF is not set")
	}

	// ✅ 3. ใช้ pgxpool.ParseConfig เพื่อสร้างคอนฟิกของ Pool
	config, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		log.Fatal("❌ Failed to parse pool config:", err)
	}

	// ✅ 4. อัปเดตวิธีเข้าถึงการตั้งค่า Simple Protocol (ต้องเข้าผ่าน ConnConfig)
	// ⚠️ Fix for "prepared statement already exists" error for Supabase
	config.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol

	// ✅ 5. สร้าง Connection Pool ด้วย NewWithConfig
	DB, err = pgxpool.NewWithConfig(context.Background(), config)
	if err != nil {
		log.Fatal("❌ DB pool connection failed:", err)
	}

	log.Println("✅ Connected to Supabase DB via Connection Pool (Simple Protocol)")
}

// ✅ [เพิ่มฟังก์ชันนี้] สำหรับ Reset Database
func ResetDatabase() {
	if DB == nil {
		log.Fatal("❌ Database connection is not initialized")
	}

	fmt.Println("⏳ Starting Database Migration...")
	ctx := context.Background()

	// 1. ลบตารางเก่า (Drop)
	_, err := DB.Exec(ctx, dropSchemaSQL)
	if err != nil {
		log.Fatalf("❌ Error dropping tables: %v", err)
	}
	fmt.Println("🔥 Old tables dropped.")

	// 2. สร้างตารางใหม่ (Create)
	_, err = DB.Exec(ctx, createSchemaSQL)
	if err != nil {
		log.Fatalf("❌ Error creating tables: %v", err)
	}
	fmt.Println("🎉 All tables created successfully!")
}

// ✅ [เพิ่มฟังก์ชันนี้] สำหรับลบ Policy ทั้งหมดและปิด RLS
func DisableRLS() {
	if DB == nil {
		log.Fatal("❌ Database connection is not initialized")
	}

	fmt.Println("⏳ Disabling Row Level Security (RLS)...")
	ctx := context.Background()

	_, err := DB.Exec(ctx, disableRLSSQL)
	if err != nil {
		log.Fatalf("❌ Error disabling RLS: %v", err)
	}

	fmt.Println("🔓 RLS Disabled & Policies Dropped successfully!")
}

// SQL สำหรับลบตาราง (เรียงย้อนศรจากลูกไปหาแม่)
const dropSchemaSQL = `
	-- ลบ Trigger/Function ของระบบ Level
    DROP TRIGGER IF EXISTS on_character_exp_change ON public.characters;
    DROP FUNCTION IF EXISTS public.handle_character_exp_update();
    DROP FUNCTION IF EXISTS public.calculate_level_from_exp(int);

	DROP TRIGGER IF EXISTS on_auth_user_created_character ON auth.users;
    DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
    DROP FUNCTION IF EXISTS public.handle_new_user_character();
    DROP FUNCTION IF EXISTS public.handle_new_user();

	DROP TABLE IF EXISTS public.receive CASCADE;
	DROP TABLE IF EXISTS public.give CASCADE;
	DROP TABLE IF EXISTS public.attain CASCADE;
	DROP TABLE IF EXISTS public.collect CASCADE;
	DROP TABLE IF EXISTS public.do_quests CASCADE;
	DROP TABLE IF EXISTS public.obtain CASCADE;
	DROP TABLE IF EXISTS public.wear CASCADE;
	DROP TABLE IF EXISTS public.take CASCADE;
	DROP TABLE IF EXISTS public.get_notifications CASCADE;
	DROP TABLE IF EXISTS public.conduct CASCADE;
	
	DROP TABLE IF EXISTS public.exams CASCADE;
	DROP TABLE IF EXISTS public.quests CASCADE;
	DROP TABLE IF EXISTS public.items CASCADE;
	DROP TABLE IF EXISTS public.characters CASCADE;
	DROP TABLE IF EXISTS public.user_profiles CASCADE;
	
	DROP TABLE IF EXISTS public.achievements CASCADE;
	DROP TABLE IF EXISTS public.categories CASCADE;
	DROP TABLE IF EXISTS public.clubs CASCADE;
	DROP TABLE IF EXISTS public.notifications CASCADE;
	DROP TABLE IF EXISTS public.maps CASCADE;
`

// SQL สำหรับสร้างตาราง (เรียงตามลำดับความสัมพันธ์)
const createSchemaSQL = `
	-- LEVEL 1: Table ที่ไม่มี FK
	CREATE TABLE public.maps (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		detail text,
		image text
	);

	CREATE TABLE public.notifications (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		title text NOT NULL,
		detail text,
		type text,
		image text,
		start_date timestamp with time zone,
		due_date timestamp with time zone
	);

	CREATE TABLE public.clubs (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		description text,
		created_at timestamp with time zone DEFAULT now()
	);

	CREATE TABLE public.categories (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		description text
	);

	CREATE TABLE public.achievements (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		description text
	);

	-- LEVEL 2: Table ที่มี FK
	CREATE TABLE public.user_profiles (
		id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
		name text,
		email text,
		detail text,
		created_at timestamp with time zone DEFAULT now(),
		club_id bigint REFERENCES public.clubs(id) ON DELETE SET NULL,
		club_join_date timestamp with time zone,
		club_role text
	);

	CREATE TABLE public.characters (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
		level int DEFAULT 1 NOT NULL,
		experience int DEFAULT 0 NOT NULL,
		gender text DEFAULT 'FEMALE' NOT NULL,
		skin_color text DEFAULT 'WHITE' NOT NULL,
		emotion text DEFAULT 'NORMAL' NOT NULL,
		body_type text DEFAULT 'KID' NOT NULL,
		intelligence int DEFAULT 10 NOT NULL,
		strength int DEFAULT 10 NOT NULL,
		creative int DEFAULT 10 NOT NULL,
		stamina int DEFAULT 100 NOT NULL CHECK (stamina >= 0 AND stamina <= 100)
	);

	CREATE TABLE public.items (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		description text,
		image text,
		rarity text,
		category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL
	);

	CREATE TABLE public.quests (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		detail text,
		image text,
		start_date timestamp with time zone,
		due_date timestamp with time zone,
		type text,
		club_id bigint REFERENCES public.clubs(id) ON DELETE SET NULL
	);

	CREATE TABLE public.exams (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		detail text,
		status text,
		type text,
		image text,
		map_id bigint REFERENCES public.maps(id) ON DELETE SET NULL
	);

	-- LEVEL 3: Many-to-Many Relations
	CREATE TABLE public.conduct (
		user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
		exam_id bigint REFERENCES public.exams(id) ON DELETE CASCADE,
		status text,
		completed_date timestamp with time zone DEFAULT now(),
		PRIMARY KEY (user_id, exam_id)
	);

	CREATE TABLE public.get_notifications ( -- เปลี่ยนชื่อจาก get เป็น get_notifications
		user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
		notification_id bigint REFERENCES public.notifications(id) ON DELETE CASCADE,
		status text,
		read_date timestamp with time zone,
		reward_claimed boolean DEFAULT false,
		PRIMARY KEY (user_id, notification_id)
	);

	CREATE TABLE public.take (
		exam_id bigint REFERENCES public.exams(id) ON DELETE CASCADE,
		item_id bigint REFERENCES public.items(id) ON DELETE CASCADE,
		status text,
		completed_date timestamp with time zone,
		reward_claimed boolean DEFAULT false,
		PRIMARY KEY (exam_id, item_id)
	);

	CREATE TABLE public.wear (
		character_id bigint REFERENCES public.characters(id) ON DELETE CASCADE,
		item_id bigint REFERENCES public.items(id) ON DELETE CASCADE,
		type text,
		PRIMARY KEY (character_id, item_id)
	);

	CREATE TABLE public.obtain (
		notification_id bigint REFERENCES public.notifications(id) ON DELETE CASCADE,
		item_id bigint REFERENCES public.items(id) ON DELETE CASCADE,
		status text,
		completed_date timestamp with time zone,
		reward_claimed boolean DEFAULT false,
		PRIMARY KEY (notification_id, item_id)
	);

	CREATE TABLE public.do_quests ( -- เปลี่ยนชื่อจาก do เป็น do_quests
		user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
		quest_id bigint REFERENCES public.quests(id) ON DELETE CASCADE,
		status text,
		completed_date timestamp with time zone,
		PRIMARY KEY (user_id, quest_id)
	);

	CREATE TABLE public.collect (
		user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
		item_id bigint REFERENCES public.items(id) ON DELETE CASCADE,
		quantity int DEFAULT 1,
		acquired_date timestamp with time zone DEFAULT now(),
		PRIMARY KEY (user_id, item_id)
	);

	CREATE TABLE public.attain (
		user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
		achievement_id bigint REFERENCES public.achievements(id) ON DELETE CASCADE,
		status text,
		completed_date timestamp with time zone,
		reward_claimed boolean DEFAULT false,
		PRIMARY KEY (user_id, achievement_id)
	);

	CREATE TABLE public.give (
		achievement_id bigint REFERENCES public.achievements(id) ON DELETE CASCADE,
		item_id bigint REFERENCES public.items(id) ON DELETE CASCADE,
		quantity int DEFAULT 1,
		acquired_date timestamp with time zone,
		PRIMARY KEY (achievement_id, item_id)
	);

	CREATE TABLE public.receive (
		quest_id bigint REFERENCES public.quests(id) ON DELETE CASCADE,
		item_id bigint REFERENCES public.items(id) ON DELETE CASCADE,
		quantity int DEFAULT 1,
		PRIMARY KEY (quest_id, item_id)
	);

	-- ==========================================
	-- 1. เปิดใช้งาน RLS ทุกตาราง
	-- ==========================================
	ALTER TABLE public.maps ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.quests ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.conduct ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.get_notifications ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.take ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.wear ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.obtain ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.do_quests ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.collect ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.attain ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.give ENABLE ROW LEVEL SECURITY;
	ALTER TABLE public.receive ENABLE ROW LEVEL SECURITY;

	-- ==========================================
	-- 2. ข้อมูลสาธารณะ (Game Data) - ดูได้ทุกคน
	-- ==========================================
	CREATE POLICY "Public read maps" ON public.maps FOR SELECT USING (true);
	CREATE POLICY "Public read notifications" ON public.notifications FOR SELECT USING (true);
	CREATE POLICY "Public read clubs" ON public.clubs FOR SELECT USING (true);
	CREATE POLICY "Public read categories" ON public.categories FOR SELECT USING (true);
	CREATE POLICY "Public read achievements" ON public.achievements FOR SELECT USING (true);
	CREATE POLICY "Public read items" ON public.items FOR SELECT USING (true);
	CREATE POLICY "Public read quests" ON public.quests FOR SELECT USING (true);
	CREATE POLICY "Public read exams" ON public.exams FOR SELECT USING (true);

	-- ตาราง Relation (Static Data)
	CREATE POLICY "Public read take" ON public.take FOR SELECT USING (true);
	CREATE POLICY "Public read obtain" ON public.obtain FOR SELECT USING (true);
	CREATE POLICY "Public read give" ON public.give FOR SELECT USING (true);
	CREATE POLICY "Public read receive" ON public.receive FOR SELECT USING (true);

	-- ==========================================
	-- 3. ข้อมูลผู้เล่น (User Data) - ดูได้ทุกคน (Public Profile)
	-- หมายเหตุ: ถ้าอยากให้เป็น Private ดูได้แค่เจ้าของ ให้แก้ USING (true) เป็น USING (auth.uid() = user_id)
	-- ==========================================
	CREATE POLICY "Public read profiles" ON public.user_profiles FOR SELECT USING (true);
	CREATE POLICY "Public read characters" ON public.characters FOR SELECT USING (true);
	CREATE POLICY "Public read wear" ON public.wear FOR SELECT USING (true);

	-- ==========================================
	-- 4. ข้อมูลความคืบหน้าส่วนตัว (Private Progress)
	-- นโยบาย: เจ้าของดูได้คนเดียว คนอื่นห้ามส่อง
	-- ==========================================
	CREATE POLICY "Owner read conduct" ON public.conduct FOR SELECT USING (auth.uid() = user_id);
	CREATE POLICY "Owner read get_notif" ON public.get_notifications FOR SELECT USING (auth.uid() = user_id);
	CREATE POLICY "Owner read do_quests" ON public.do_quests FOR SELECT USING (auth.uid() = user_id);
	CREATE POLICY "Owner read inventory" ON public.collect FOR SELECT USING (auth.uid() = user_id);
	CREATE POLICY "Owner read attain" ON public.attain FOR SELECT USING (auth.uid() = user_id);

	-- ⚠️ ไม่มี Policy สำหรับ INSERT / UPDATE / DELETE เลย 
	-- แปลว่า Client ทำอะไรไม่ได้นอกจากดู

	-- ==========================================
    -- [เพิ่มส่วนนี้] 5. ระบบ Automation (Triggers & Functions)
    -- ทำงานเมื่อมี User สมัครใหม่ -> สร้าง Profile และ Character ให้ทันที
    -- ==========================================

    -- 5.1 ฟังก์ชันสร้าง User Profile
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger AS $$
    BEGIN
        -- หมายเหตุ: แก้ชื่อ column ให้ตรงกับตาราง user_profiles (id, email, name)
        INSERT INTO public.user_profiles (id, email, name)
        VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
        RETURN new;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;

    -- 5.2 Trigger สั่งงานสร้าง Profile
    CREATE TRIGGER on_auth_user_created
        AFTER INSERT ON auth.users
        FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

    -- 5.3 ฟังก์ชันสร้าง Character เริ่มต้น
    CREATE OR REPLACE FUNCTION public.handle_new_user_character()
    RETURNS trigger AS $$
    DECLARE
        char_id bigint; -- ตัวแปรเก็บ ID ของ Character ที่เพิ่งสร้าง
    BEGIN
        -- 1. สร้าง Character ปกติ และเก็บ ID ไว้ใว้ตัวแปร char_id
        INSERT INTO public.characters (user_id)
        VALUES (new.id)
        RETURNING id INTO char_id;
        
        -- 2. แจก Item เริ่มต้น (ชื่อลงท้ายด้วย _00) เข้ากระเป๋า User (Table: collect)
        INSERT INTO public.collect (user_id, item_id, quantity)
        SELECT new.id, id, 1 
        FROM public.items 
        WHERE name LIKE '%_00';

        -- 3. สวมใส่ Item เริ่มต้น (Table: wear) ให้ Character ทันที
        INSERT INTO public.wear (character_id, item_id, type)
        SELECT char_id, i.id, c.name
        FROM public.items i
        JOIN public.categories c ON i.category_id = c.id
        WHERE i.name LIKE '%_00';

        RETURN new;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;

    -- 5.4 Trigger สั่งงานสร้าง Character
    CREATE TRIGGER on_auth_user_created_character
        AFTER INSERT ON auth.users
        FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user_character();
	
	-- ==========================================
    -- [เพิ่มส่วนนี้] 6. ระบบคำนวณ Level อัตโนมัติ (Auto Level Up)
    -- ==========================================

    -- 6.1 Logic Function: รับค่า Total EXP -> คืนค่า Level ที่ควรจะเป็น
    CREATE OR REPLACE FUNCTION public.calculate_level_from_exp(total_exp int) 
    RETURNS int AS $$
    DECLARE
        curr_level int := 1;
        req_exp int := 0;
        remaining_exp int := total_exp;
    BEGIN
        LOOP
            IF curr_level < 6 THEN
                req_exp := 40 * curr_level; -- Level 1-5
            ELSE
                req_exp := 200 + (curr_level * curr_level); -- Level 6+
            END IF;

            IF remaining_exp >= req_exp THEN
                remaining_exp := remaining_exp - req_exp;
                curr_level := curr_level + 1;
            ELSE
                EXIT; 
            END IF;
        END LOOP;
        RETURN curr_level;
    END;
    $$ LANGUAGE plpgsql;

    -- 6.2 Trigger Function: ตัวสั่งงานเมื่อมีการแก้ไข EXP
    CREATE OR REPLACE FUNCTION public.handle_character_exp_update()
    RETURNS trigger AS $$
    BEGIN
        -- คำนวณ Level ใหม่และยัดใส่ row ที่กำลังจะบันทึก
        NEW.level := public.calculate_level_from_exp(NEW.experience);
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    -- 6.3 Trigger: ติดตั้งลงในตาราง characters
    CREATE TRIGGER on_character_exp_change
    BEFORE UPDATE OF experience ON public.characters
    FOR EACH ROW
    EXECUTE PROCEDURE public.handle_character_exp_update();

	-- ==========================================
    -- [เพิ่มส่วนนี้] 7. Seed Data (ข้อมูลเริ่มต้น)
    -- ==========================================
    INSERT INTO public.categories (name, description) VALUES 
    ('Skin', 'Skin Color'),
    ('Hair', 'Hairstyle'),
    ('Face', 'Facial Expression'),
    ('Outfit', 'Full Body Outfit');

    -- Item Default (ลงท้ายด้วย _00 เพื่อให้ตรงกับ Animation Name ใน Rive)
    INSERT INTO public.items (name, description, rarity, category_id) VALUES
    ('Skin_00', 'Default Skin', 'COMMON', (SELECT id FROM public.categories WHERE name='Skin')),
    ('Hair_00', 'Default Hair', 'COMMON', (SELECT id FROM public.categories WHERE name='Hair')),
    ('Face_00', 'Default Face', 'COMMON', (SELECT id FROM public.categories WHERE name='Face')),
    ('Outfit_00', 'Default Outfit', 'COMMON', (SELECT id FROM public.categories WHERE name='Outfit'));
`
const disableRLSSQL = `
	-- 1. ลบ Policy ทั้งหมดใน Schema 'public' แบบอัตโนมัติ
	-- เราใช้ PL/pgSQL วนลูปหา Policy ทั้งหมดแล้วสั่ง DROP
	DO $$ 
	DECLARE 
		r RECORD;
	BEGIN 
		FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') 
		LOOP 
			EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename); 
		END LOOP; 
	END $$;

	-- 2. สั่งปิด RLS ของทุกตาราง (เรียงตามลำดับที่คุณมี)
	ALTER TABLE public.maps DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.clubs DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.achievements DISABLE ROW LEVEL SECURITY;
	
	ALTER TABLE public.user_profiles DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.characters DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.quests DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.exams DISABLE ROW LEVEL SECURITY;
	
	ALTER TABLE public.conduct DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.get_notifications DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.take DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.wear DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.obtain DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.do_quests DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.collect DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.attain DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.give DISABLE ROW LEVEL SECURITY;
	ALTER TABLE public.receive DISABLE ROW LEVEL SECURITY;
`
